Remove m_singleParameterResizeIndex from ArrayView to reduce memory.
GEOS-DEV/LvArray pull request #311
Opened 2024-01-10 19:54 UTC by dkachuma

- `m_singleParameterResizeIndex` is replaced by a `constexpr` value hard-coded to 0.
- Two interface methods are removed:
  *  `int ArrayView::getSingleParameterResizeIndex() const`
  * `void Array::setSingleParameterResizeIndex( int const index )`

2024-01-16 22:12 UTC, corbett5 commented on src/Array.hpp
> +   * @details Sets the size of singleParameterResizeIndex to 0 but leaves the
Also change these docs, to reflect that you removed `singleParameterResizeIndex`.

2024-01-16 22:13 UTC, corbett5 requested changes

2024-01-16 22:13 UTC, corbett5 commented on src/ArrayView.hpp
> +  static constexpr int singleParameterResizeIndex = 0;
I would remove this all together.

2024-01-16 22:58 UTC, corbett5 commented on src/python/PyArray.cpp
I'm glad you compiled the python interface, because I forgot this would require some changes here. Thanks!

2024-01-17 21:01 UTC, corbett5 reviewed
Looks good to me! If the tests are passing (the python interface tests as well) it is a welcome change!

2024-01-17 21:01 UTC, corbett5 commented on src/MallocBuffer.hpp
> +#if (defined(__GNUC__) && (__GNUC__ == 8))
These seem unrelated, correct?

2024-01-17 21:10 UTC, dkachuma commented on src/MallocBuffer.hpp
> +#if (defined(__GNUC__) && (__GNUC__ == 8))
Yes. I encountered an unrelated compile issue with gcc8 on my machine. Apparently there was a bug with gcc8 which makes it issue a potentially false warning if the argument to `std::malloc` is not checked.

2024-01-26 17:18 UTC, corbett5 approved these changes

2024-02-06 18:56 UTC, merged